tika:
  parsers:
    tesseract-ocr:
      language: eng
      timeout: 120
      enable-image-processing: false
      apply-rotation: false

    pdf-ocr-parser:
      ocr-only-strategy: true
      min-doc-text-length: 100
      min-doc-byte-size: 10000
      use-legacy-ocr-parser-for-single-page-doc: false

    legacy-pdf-parser:
      image-magick:
        timeout: 120
      tesseract-ocr:
        timeout: 120
      min-doc-text-length: 100
