# application configuration
#
application:
  version: 0.3.0

# general spring boot and server configuration
#
server:
  port: 8090
  tomcat:
    threads:
      max: 8

spring:
  servlet:
    multipart.max-file-size: 32768MB
    multipart.max-request-size: 32768MB
    multipart.file-size-threshold: 128MB
    multipart.enabled: true

# tika configuration
#
tika:
  parsers:
    tesseract-ocr:
      language: eng
      timeout: 1200
      enable-image-processing: true
      apply-rotation: false
      resize: 100
      density: 300
      depth: 4
      filter: "triangle"

    pdf-ocr-parser:
      ocr-only-strategy: false
      min-doc-text-length: 10
      min-doc-byte-size: 100
      apply-rotation: false
      ocr-detect-angles: false
      ocr-dpi: 100
      use-legacy-ocr-parser-for-single-page-doc: false

    legacy-pdf-parser:
      image-magick:
        timeout: 1200
      tesseract-ocr:
        timeout: 1200
      min-doc-text-length: 0
  bulk:
    num-consumers: 16

# documents processing configuration
#
processing:
  use-legacy-tika-processor-as-default: false
  fail-on-empty-files: false
  fail-on-non-document-types: false

logging:
  level:
    root: DEBUG
    tika.processor: DEBUG
    org.springframework.web: DEBUG
    service.controller: DEBUG
    org.hibernate: INFO
  file:
    path: "./"
    name: "app.log"
