# application configuration
#
application:
  version: 0.3.0

# general spring boot and server configuration
#
server:
  port: 8090
  tomcat:
    threads:
      max: 16

spring:
  servlet:
    multipart.max-file-size: 32768MB
    multipart.max-request-size: 32768MB
    multipart.file-size-threshold: 128MB
    multipart.enabled: true

# tika configuration
#
tika:
  parsers:
    tesseract-ocr:
      language: eng
      timeout: 1200
      enable-image-processing: true
      apply-rotation: false

    pdf-ocr-parser:
      ocr-only-strategy: false
      min-doc-text-length: 1
      min-doc-byte-size: 10
      apply-rotation: false
      use-legacy-ocr-parser-for-single-page-doc: false

    legacy-pdf-parser:
      image-magick:
        timeout: 1200
      tesseract-ocr:
        timeout: 1200
      min-doc-text-length: 1
  bulk:
    num-consumers: 16

# documents processing configuration
#
processing:
  use-legacy-tika-processor-as-default: false
  fail-on-empty-files: false
  fail-on-non-document-types: false

logging:
  level:
    root: INFO
    tika.processor: INFO
    org.springframework.web: INFO
    service.controller: INFO
    org.hibernate: INFO
  file:
    path: "./"
    name: "app.log"
