version: '3.5'

services:
  tika-service:
    build: ..
    environment:
      # limit the number of processing threads used by tesseract OCR,
      # this should be used with care as processing for smaller documents (i.e < 10mb) is faster when limiting threads as
      # the thread IPC and management does not interfere when u sing a single thread
      - OMP_THREAD_LIMIT=0
    volumes:
    - ../src/main/resources/application.yaml:/app/config/application.yaml:ro
    ports:
    - "8090:8090"