version: '3.5'

services:
  tika-service:
    container_name: cogstack-tika-service
    #image: cogstacksystems/tika-service:latest
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    environment:
      # limit the number of processing threads used by tesseract OCR,
      # this should be used with care as processing for smaller documents (i.e < 10mb) is faster when limiting threads as
      # the thread IPC and management does not interfere when using a single thread
      # leave it to 1 if documents are small ( < 10mb) otherwise change to 0
      - "OMP_THREAD_LIMIT=0"
    volumes:
    - ../src/main/resources/application.yaml:/app/config/application.yaml:ro
    #ports:
    #- "8090:8090"
    command: ""
    # comment network_mode if you wish to use another port and uncomment the ports section
    network_mode: host