name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install dependencies
        run: |
          sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu fossa main restricted " && \
          sudo apt-add-repository "deb-src http://archive.ubuntu.com/ubuntu fossa main restricted multiverse universe" && \
          sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu fossa-updates main" && \
          sudo apt-add-repository "deb-src http://archive.ubuntu.com/ubuntu fossa-updates main multiverse universe" && \
          sudo apt-get update && sudo apt-get upgrade -y && sudo apt dist-upgrade -y && \
          sudo apt-get install -y curl apt-transport-https apt-utils software-properties-common \
          imagemagick ghostscript tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd tesseract-ocr-lat tesseract-ocr-fra tesseract-ocr-deu \
          libtomcat9-java libtomcat9-embed-java libtcnative-1 python3-pip

      - name: Install python packages
        run: sudo -H pip3 install numpy matplotlib scikit-image

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew build